"""Record what each engine stage does, for the explorer's live widgets.

    python -m scripts.gen_explorer_demos            # print the JSON
    python -m scripts.gen_explorer_demos --write    # splice it into explorer.html

The page runs NOTHING (see `gen_ingest_demo.py` for why): it replays what the
REAL code produced for a fixed set of INVENTED commands. Five islands:

    seg       segmentation — the pieces a command is cut into, with the time
              phrase each piece owns and its kind, plus the time spans found
    resolve   decompose_validate — a time phrase in, every value out
    fastrule  the front door — handled, deferred or refused, and why
    chain     the whole chain — X0..X4 and the trace, one command at a time
              (recorded WITH the model, so this island is checked for shape,
              not equality)
    eval      the numbers the boards banked, for the charts

`seg`, `resolve` and `fastrule` are deterministic and model-free;
`tests/unit/test_artifact_claims.py` regenerates them and fails if the page's
copy differs. Every command here is invented and carries no personal word —
the page's leak check covers whatever this writes.
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import os
import pathlib
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
PAGE = ROOT / "DOCUMENTATION" / "artifacts" / "explorer.html"
MARK_OPEN = "<!-- EXPLORER-DEMOS:BEGIN (generated by scripts/gen_explorer_demos.py) -->"
MARK_CLOSE = "<!-- EXPLORER-DEMOS:END -->"

_T = tempfile.mkdtemp(prefix="explorer_demos_")
for _v in ("DB", "MEMORY_DB", "VOCAB", "CATEGORIES", "TRACE_BUS", "MODELS",
           "LABEL_FEEDBACK", "MODEL_LOCK", "DEVICE_SECRET", "DEVICES",
           "CHECKPOINTS", "LEXICON", "UI_STATE", "LOCATION"):
    os.environ[f"MACALENDAR_{_v}"] = os.path.join(_T, _v.lower())
os.environ["MACALENDAR_NO_WARMUP"] = "1"
os.environ.setdefault("MACALENDAR_LLM_PRIORITY", "background")

#: A Wednesday, so "tomorrow", "this thursday" and "next week" all mean
#: something definite on the page and stay the same on every regeneration.
CLOCK = dt.datetime(2026, 9, 9, 11, 0)

SEG_COMMANDS = [
    ("two asks, one breath", "book the dentist tomorrow at 4pm and remind me to buy milk"),
    ("a leading day covers both", "tomorrow gym at 7 and a haircut at 11"),
    ("a trailing deadline covers both", "submit the grades and prepare the slides by friday"),
    ("a list is one to-do", "buy milk, eggs and bread"),
    ("three things is three events", "on friday create an event for the dentist, a haircut and the gym"),
    ("a comma run is one thing", "set a meeting on sunday for 1 p.m. office hour, meeting"),
    ("a question and an ask", "what do I have this weekend and book the haircut at 3:45"),
    ("said with a stutter", "remind me me to prepare the presentation on monday"),
]

RESOLVE_PHRASES = [
    "tomorrow at 4pm", "at 7", "at 8 in the morning", "at 910am", "for 830",
    "at 1 p.m.", "next tuesday at 11", "this coming thursday", "on the 15th",
    "from 2 to 4", "for two hours", "every tuesday and thursday at 9",
    "every other week", "until the end of september", "lunch", "dinner tomorrow",
    "tonight", "in three days", "at noon", "at half past six", "tomorrow morning",
    "at 5 p.m. on sunday", "monday the 13th", "at 25pm",
]

FASTRULE_COMMANDS = [
    ("one clean ask", "book the dentist tomorrow at 4pm"),
    ("a to-do", "remind me to buy milk"),
    ("a compound, handed up", "book the gym at 6 and remind me to buy milk"),
    ("a bare kind, committed (Q42)", "add an event for 5 p.m."),
    ("a generic target, refused", "add this on my calendar"),
    ("a question, not a create", "should I add yoga tomorrow?"),
    ("a delete with no target", "just delete it"),
    ("an all-day day", "conference all day friday"),
]

CHAIN_COMMANDS = [
    ("the fast path", "book the dentist tomorrow at 4pm"),
    ("a compound on the deep path", "book the gym at 6 and remind me to buy milk"),
    ("three things, rewritten one per thing", "on friday create an event for the dentist, a haircut and the gym"),
    ("a seam inside one ask", "take out the trash. also, put milk on my shopping list"),
    ("a subject that names nothing", "add this on my calendar"),
    ("disfluent, then clean", "set a date for tomorrow at 11 o'clock, one moment, bear with me, the dentist"),
]


def _kind_class(reason: str | None) -> str:
    if not reason:
        return "handled"
    from assistant.engine.fastrule import fastrule as fr
    return {fr.REFUSAL: "refused"}.get(fr.reason_class(reason), "deferred")


def build_seg() -> list:
    import importlib
    FS = importlib.import_module("assistant.engine.segmentation.fastseg.fastseg")
    out = []
    for label, text in SEG_COMMANDS:
        refs = [{"text": r.text, "kind": r.kind, "start": r.start, "end": r.end}
                for r in FS.find_time_refs(text)]
        items = FS.fastseg(text)
        out.append({"label": label, "text": text, "refs": refs,
                    "items": [{"action": i["action"], "time": i["time"], "tag": i["tag"],
                               "source": i["source"]} for i in items]})
    return out


def build_resolve() -> list:
    from assistant.engine.decompose_validate import resolve as R
    out = []
    for phrase in RESOLVE_PHRASES:
        got = R.resolve(phrase, CLOCK.date(), f"dentist {phrase}", action="dentist")
        row = {k: got.get(k) for k in ("date", "start_time", "end_time", "recurrence",
                                        "recur_days", "recur_until", "recurrence_rounded")}
        if isinstance(row["date"], str) and "T" in row["date"]:
            row["date"] = row["date"][:10]
        out.append({"phrase": phrase, "values": row})
    return out


def build_fastrule() -> list:
    from assistant.engine.fastrule import fastrule as fr
    from freezegun import freeze_time
    out = []
    from assistant.intent.rule_parser import RULE_THRESHOLD
    with freeze_time(CLOCK):
        front = fr.FastRule(RULE_THRESHOLD)
        for label, text in FASTRULE_COMMANDS:
            res = front.run(text)
            objs = []
            for name, intent in (res.intents or []):
                objs.append({"action": name,
                             "title": getattr(intent, "title", None)
                                      or (getattr(intent, "titles", None) or [None])[0]
                                      or getattr(intent, "match_title", None),
                             "date": getattr(intent, "date", None),
                             "start_time": getattr(intent, "start_time", None),
                             "end_time": getattr(intent, "end_time", None)})
            out.append({"label": label, "text": text, "committed": bool(res.committed),
                        "confidence": round(float(res.confidence or 0), 2),
                        "reason": res.reason, "class": _kind_class(res.reason),
                        "objects": objs})
    return out


def build_chain() -> list:
    """WITH the model: the deep rows need the rescue. Shape-checked only."""
    import re
    from freezegun import freeze_time
    import assistant.engine as engine
    from assistant.engine import llm as _llm
    _llm.get_rule_parser().analyze("book gym tomorrow at 7am", current_view="month")
    out = []
    with freeze_time(CLOCK, tick=True):
        for label, text in CHAIN_COMMANDS:
            reply = engine.run_transcript(text, source="test")
            bounds = [{"name": b.get("name"), "value": str(b.get("value"))[:240]}
                      for b in (reply.get("boundaries") or [])]
            steps = [{"stage": s.get("stage"), "title": s.get("title"),
                      "detail": str(s.get("detail") or "")[:200], "ok": bool(s.get("ok", True)),
                      "outcome": ((s.get("data") or {}).get("outcome") or "")}
                     for s in (reply.get("trace") or [])
                     if s.get("stage") not in ("stt", "memory")]
            out.append({"label": label, "text": text, "parse": reply.get("parse"),
                        "message": re.sub(r"\s+", " ", reply.get("message") or "")[:300],
                        "boundaries": bounds, "steps": steps,
                        "hint": (reply.get("hint") or {}).get("code") or ""})
    return out


def build_eval() -> dict:
    """The banked numbers, read from the records that banked them."""
    dev = []
    with open(ROOT / "dataset" / "loop_log.csv") as fh:
        for r in csv.DictReader(fh):
            if r.get("slice") == "dev-100" and r.get("era") == "2" and r.get("overall_pct"):
                dev.append({"run": int(r["run"]), "pct": float(r["overall_pct"]),
                            "date": r["started_at"][:10]})
    sealed = [  # the sweep table (checkpoints/RUN_STATUS.md) and the two milestones
        {"state": "old brain", "pct": 79.0}, {"state": "FastRule v1", "pct": 79.7},
        {"state": "decompose-validate v1", "pct": 75.3}, {"state": "main 09-12", "pct": 77.3},
        {"state": "one-shot (control)", "pct": 66.0}, {"state": "2026-09-22", "pct": 73.0},
    ]
    real = {"generic_title": [52.4, 90.5], "corrected_count": [60.0, 73.3],
            "corrected_fields": [13.3, 20.0], "approved": [64.7, 64.7]}
    board_d = None
    runs = sorted((ROOT / "assistant" / "engine" / "llmjudge" / "experiments" / "runs").glob("board_d_train_*.json"))
    if runs:
        board_d = json.loads(runs[-1].read_text())
        board_d = {"n": board_d["n"], "off": board_d["off_pct"], "on": board_d["on_pct"],
                   "fixed": board_d["fixed"], "broke": board_d["broke"],
                   "disagreed": board_d["disagreed"],
                   "by_reentries": board_d["by"].get("reentries", {})}
    return {"dev100": dev[-12:], "sealed": sealed, "real_usage": real, "board_d": board_d}


def build_deterministic() -> dict:
    return {"seg": build_seg(), "resolve": build_resolve(), "fastrule": build_fastrule()}


def build(with_model: bool = True) -> dict:
    data = build_deterministic()
    data["eval"] = build_eval()
    data["chain"] = build_chain() if with_model else []
    data["clock"] = CLOCK.isoformat()
    return data


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--no-model", action="store_true", help="skip the chain island")
    a = ap.parse_args()
    data = build(with_model=not a.no_model)
    blob = json.dumps(data, ensure_ascii=False, indent=1)
    if not a.write:
        print(blob)
        return 0
    page = PAGE.read_text()
    payload = (f"{MARK_OPEN}\n"
               f'<script id="explorer-demos" type="application/json">\n{blob}\n</script>\n')
    if MARK_OPEN in page:
        start, end = page.index(MARK_OPEN), page.index(MARK_CLOSE)
        page = page[:start] + payload + page[end:]
    else:
        page = page.replace("</body>", payload + MARK_CLOSE + "\n</body>", 1)
    PAGE.write_text(page)
    print(f"spliced {len(data['seg'])} seg · {len(data['resolve'])} resolve · "
          f"{len(data['fastrule'])} fastrule · {len(data['chain'])} chain examples into {PAGE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
