"""Generate the explorer's INGEST walkthrough data by running the real code.

    python -m scripts.gen_ingest_demo            # print the JSON
    python -m scripts.gen_ingest_demo --write    # splice it into explorer.html

WHY IT IS GENERATED AND NOT WRITTEN IN JAVASCRIPT. The obvious way to make the
page interactive is to port the cleanup regexes to JS and run them in the
browser. That is a second implementation of a thing this project already has
one of, and this session alone has spent hours on two implementations of one
rule disagreeing — the kind board scoring a dead component, the tagger and the
front door answering differently about the same sentence, two recurrence
readers where the looser one committed. A page that reimplements the engine
would drift the same way and nobody would notice, because a page has no tests
of its own.

So the browser runs NOTHING. It steps through a recording of what the REAL
passes did, in order. `tests/unit/test_artifact_claims.py` regenerates this and
fails if the embedded copy disagrees, so a change to `cleanup.py` that moves
the walkthrough turns the build red rather than quietly leaving the page
describing an engine that no longer exists.

THE PASS ORDER IS VERIFIED, NOT ASSUMED. This file applies the same pattern
objects in the order `strip_spoken_noise` applies them, then asserts its own
final string equals what the real function returns. If someone reorders the
passes there and not here, this raises rather than emitting a plausible lie.
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
PAGE = ROOT / "DOCUMENTATION" / "artifacts" / "explorer.html"
MARK_OPEN = "<!-- INGEST-DEMO:BEGIN (generated by scripts/gen_ingest_demo.py) -->"
MARK_CLOSE = "<!-- INGEST-DEMO:END -->"

_T = tempfile.mkdtemp(prefix="ingest_demo_")
for _v in ("DB", "MEMORY_DB", "VOCAB", "CATEGORIES", "TRACE_BUS", "MODELS",
           "LABEL_FEEDBACK", "DEVICE_SECRET", "DEVICES",
           "CHECKPOINTS", "LEXICON", "UI_STATE", "LOCATION"):
    os.environ[f"MACALENDAR_{_v}"] = os.path.join(_T, _v.lower())
os.environ["MACALENDAR_NO_WARMUP"] = "1"
os.environ.setdefault("MACALENDAR_LLM_PRIORITY", "background")

#: The vocabulary the walkthrough assumes. Invented terms — nothing personal
#: reaches a published page (ARTIFACT_BUILDER.md), which the leak check in
#: `test_artifact_claims` already enforces for every word on it.
#: CHECKED AGAINST THE REAL WORD LIST BEFORE BEING CHOSEN. The first draft used
#: "poker night" — and `test_no_personal_word_list_entry_reaches_a_published_page`
#: went red, because both of those words are in Gil's own vocabulary. That check
#: exists precisely because four personal words once survived a manual sweep, and
#: it caught this one before the page was published rather than after.
DEMO_VOCAB = ["barista course", "kombucha order", "sudoku club"]

EXAMPLES = [
    {"id": "opener",
     "label": "an opener and a hedge",
     "text": "um so add lunch tomorrow, or something"},
    {"id": "stutter",
     "label": "a stutter",
     "text": "remind me me to prepare the presentation"},
    {"id": "filler",
     "label": "an interrupting filler",
     "text": "um, can you you know, remind me to clean the kitchen"},
    {"id": "multiword",
     "label": "a term whose boundaries moved",
     "text": "book bar rista course on friday"},
    {"id": "joined",
     "label": "two words run together",
     "text": "add sue dough coup club to my calendar"},
    {"id": "stopword",
     "label": "a stop keyword",
     "text": "add milk to my list, done, execute"},
    {"id": "falsestart",
     "label": "a false start",
     "text": "um, no wait"},
]


def trace(text: str, store) -> "list[dict]":
    """[{pass, title, note, text}] — the transcript after each real pass."""
    from assistant.intent import cleanup as C
    from assistant.engine.ingest import repair as R

    steps = [{"pass": "heard", "title": "what Whisper wrote",
              "note": "the raw transcript", "text": text}]

    cur = R._peel_stop_keywords(text, None) or text
    steps.append({"pass": "stop", "title": "stop keyword",
                  "note": "the phrase that ends dictation, peeled until none is left",
                  "text": cur})

    # The same objects `strip_spoken_noise` uses, in its order. Verified below.
    cur2 = C._OPENERS.sub("", cur.strip())
    steps.append({"pass": "openers", "title": "openers",
                  "note": "words that announce speech rather than a request",
                  "text": cur2})
    cur3 = C._NOW_OPENER.sub("", cur2)
    steps.append({"pass": "now", "title": '"now,"',
                  "note": 'only with the comma — "do it now" is a real time word',
                  "text": cur3})
    cur4 = cur3
    for _ in range(8):
        nxt = C._FILLER_PHRASE.sub("", cur4)
        if nxt == cur4:
            break
        cur4 = nxt
    steps.append({"pass": "filler", "title": "filler phrases",
                  "note": '"you know,", "one moment," — a trailing comma is required; '
                          '"i mean," only without a comma before it',
                  "text": cur4})
    cur5 = C._STUTTER.sub(r"\1", cur4)
    steps.append({"pass": "stutter", "title": "stutter",
                  "note": "the same word twice; AFTER fillers, because "
                          '"you you know" is "you" plus a filler',
                  "text": cur5})
    cur6 = C._TRAILING_HEDGE.sub("", cur5)
    steps.append({"pass": "hedge", "title": "trailing hedge",
                  "note": '"…or something", "…i guess"', "text": cur6})
    cur6b = C._TRAILING_INTERJECTION.sub("", cur6)
    steps.append({"pass": "interjection", "title": "trailing interjection",
                  "note": '"…. excuse me. excuse me." — said to nobody, after punctuation',
                  "text": cur6b})
    cur6c = C._WORD_SWAP_CORRECTION.sub(r"\2", cur6b)
    steps.append({"pass": "swap", "title": "one-word swap",
                  "note": '"with nina sorry, i mean leo" — the word before is replaced',
                  "text": cur6c})
    cur7 = cur6c
    m = C._SELF_CORRECTION.search(cur7)
    if m:
        tail = cur7[m.end():]
        if len(tail.split()) >= 2:
            cur7 = tail
    cur7 = cur7.strip(" ,;")
    steps.append({"pass": "correction", "title": "self-correction",
                  "note": "what precedes the marker is retracted", "text": cur7})

    # THE VERIFICATION. If the real function disagrees, the order here is wrong.
    real = C.strip_spoken_noise(cur, drop_courtesy=False)
    if real.strip() != cur7.strip():
        raise SystemExit(
            f"pass order drifted from strip_spoken_noise:\n"
            f"  this file: {cur7!r}\n  the engine: {real!r}")

    trivial = R.is_trivial_transcript(cur7)
    steps.append({"pass": "falsestart", "title": "false start?",
                  "note": ("fewer than two meaningful words — ignored, and NOT "
                           "remembered" if trivial else "two or more meaningful "
                           "words, so it is a command"),
                  "text": cur7, "ignored": trivial})

    fixed, corrections = store.correct(cur7)
    steps.append({"pass": "vocab", "title": "personal vocabulary",
                  "note": (", ".join(f"{c.original} → {c.replacement}"
                                     for c in corrections)
                           or "nothing it was confident about"),
                  "text": fixed})
    return steps


def build() -> dict:
    from assistant.stt.vocab import VocabStore
    store = VocabStore(os.path.join(_T, "demo_vocab.json"))
    for word in DEMO_VOCAB:
        store.add_word(word)
    return {"vocab": DEMO_VOCAB,
            "examples": [{"id": e["id"], "label": e["label"],
                          "steps": trace(e["text"], store)} for e in EXAMPLES]}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    data = build()
    blob = json.dumps(data, ensure_ascii=False, indent=1)
    if not a.write:
        print(blob)
        return 0
    page = PAGE.read_text()
    start, end = page.index(MARK_OPEN), page.index(MARK_CLOSE)
    payload = (f'{MARK_OPEN}\n'
               f'<script id="ingest-demo" type="application/json">\n{blob}\n</script>\n')
    PAGE.write_text(page[:start] + payload + page[end:])
    print(f"spliced {len(data['examples'])} examples into {PAGE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
