"""Writes MACalendar-iOS/MACalendar-iOS/DefaultRules.swift: the Mac's DEFAULT
category and tag tables, compiled into the phone, for a phone with no Mac
("This phone only") or one that has never reached it. The Mac's served
tables replace them the moment it is reached. `test_phone_default_rules`
fails if this file is out of date — rerun: python -m scripts.gen_phone_rules
"""
from __future__ import annotations

import json
import pathlib

from assistant.actions.calendar import categories as C
from assistant.actions.todo import tagging as T

OUT = pathlib.Path(__file__).resolve().parents[1] / "MACalendar-iOS/MACalendar-iOS/DefaultRules.swift"


def payloads() -> dict:
    cats = [{"name": c["name"], "color": c["color"], "alt": c.get("alt", c["color"]), "keywords": list(c["keywords"])}
            for c in C.DEFAULTS]
    return {
        "category_rules": {"rev": "bundled", "categories": cats, "people": []},
        "tag_rules": {"rev": "bundled", "keywords": T.KEYWORDS, "order": list(T.KEYWORDS),
                      "never_infer": sorted(T._NEVER_INFER), "palette": list(T.KEYWORDS) + ["Personal"],
                      "personal_labels": []},
    }


def render() -> str:
    body = json.dumps(payloads(), sort_keys=True, ensure_ascii=False)
    return (
        "// GENERATED by scripts/gen_phone_rules.py — do not edit by hand.\n"
        "// The Mac's default category and tag tables, for a phone with no Mac yet.\n"
        "import Foundation\n\n"
        "enum DefaultRules {\n"
        f"    static let json = ##\"{body}\"##\n\n"
        "    private struct Both: Decodable { let category_rules: CategoryRules; let tag_rules: TagRules }\n"
        "    private static let both = try? JSONDecoder().decode(Both.self, from: Data(json.utf8))\n"
        "    static var categoryRules: CategoryRules? { both?.category_rules }\n"
        "    static var tagRules: TagRules? { both?.tag_rules }\n"
        "}\n"
    )


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT}")
