"""Write the phone's copy of the title-icon lexicon — GENERATED, never edit by hand.

    python -m scripts.gen_title_icons_swift

`assistant/engine/label/title_icons.py` is the lexicon (which words get which
drawing, and the neighbours that confirm or veto a sense). The Mac serves each
row's `icons`; a phone with no Mac (DEVQA Q85) has to work them out itself, so
it carries the same lexicon as data: `MACalendar-iOS/Engine/TitleIconsData.swift`,
read by `TitleIcons.swift`. `tests/unit/test_title_icons.py` fails the build
when the two disagree, naming this command.
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "MACalendar-iOS" / "MACalendar-iOS" / "Engine" / "TitleIconsData.swift"


def render() -> str:
    from assistant.engine.label.title_icons import GROUP_ICONS, GROUPS, LEXICON

    def lit(s: str) -> str:
        return json.dumps(s, ensure_ascii=False)          # a JSON string is a valid Swift string literal

    lines = [
        "// GENERATED by scripts/gen_title_icons_swift.py from",
        "// assistant/engine/label/title_icons.py — do not edit by hand.",
        "// tests/unit/test_title_icons.py keeps the two equal.",
        "",
        "enum TitleIconsData {",
        "    struct Entry { let group: String; let icon: String; let words: [String]; let needs: [String]; let vetoes: [String] }",
        "",
        "    static let groups: [String] = [" + ", ".join(lit(g) for g in GROUPS) + "]",
        "    static let groupIcons: [String: String] = [" + ", ".join(f"{lit(k)}: {lit(v)}" for k, v in GROUP_ICONS.items()) + "]",
        "",
        "    static let lexicon: [Entry] = [",
    ]
    for e in LEXICON:
        lines.append(f"        Entry(group: {lit(e.group)}, icon: {lit(e.icon)},")
        lines.append(f"              words: [{', '.join(lit(w) for w in e.words)}],")
        lines.append(f"              needs: [{', '.join(lit(n) for n in e.needs)}],")
        lines.append(f"              vetoes: [{', '.join(lit(v) for v in e.vetoes)}]),")
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def main() -> int:
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
