"""The phone's compiled-in category and tag tables (`DefaultRules.swift`) are
the Mac's DEFAULTS — what a phone with no Mac ("This phone only") labels with.
Generated by `scripts/gen_phone_rules.py`; this fails when they drift."""
from __future__ import annotations

from scripts import gen_phone_rules as G


def test_the_phone_carries_the_macs_default_tables():
    assert G.OUT.read_text() == G.render(), "rerun: python -m scripts.gen_phone_rules"
